import Head from 'next/head';
import { PostCard, PostWidget, Categories } from '../components';

const posts = [
  { title: 'React Testing', excerpt: 'Learn React Testing' },
  { title: 'React with Tailwind', excerpt: 'Learn React with Tailwind CSS' },
];

export default function Home() {
  return (
    <div className='container mx-auto px-10 mb-8 bg-gray-200'>
      <Head>
        <title>MVK Blog</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post, idx) => (
            <PostCard post={post} key={post.title} />
          ))}
        </div>
        <div className='lg:col-span-4 col-span-1'>
          <div className='lg:sticky relative top-8'>
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
}
